### ISSUE TITLE
"back to the preview page" button

### ISSUE THREAD

**Issue by benhuangbmj** [flushingtech/Votte_Frontend#13]
**What**: The UI doesn't have button to go back to the previous page. Meanwhile, the backward arrow ![backto](https://github.com/user-attachments/assets/82982a83-18a9-432a-a4a8-77e9150c7712) brings the user to [flushingtech.org](https://flushingtech.org). This can feel confusing at times.

**Comment by gent1999** [comment]
Added a back to home button
