### ISSUE TITLE
Upcoming Events Page

### ISSUE THREAD

**Issue by simk209** [flushingtech/Votte_Frontend#3]
We need a page housing upcoming events so that votes and submissions can be associated with a specific hackathon event. The design of this page should make it clear which events are virtual and which are in person, and the date of each event. When the event card is clicked on, it should redirect you to the voting/submissions page for that specific event. 

Backend considerations - We will likely need a new Events table with Date and Event-Type fields. We may also need an additional field in the ideas table for the event_id. We will also need to ensure that the event records are all up to date and in sync with what is posted on meetup - consider using a chron job for this. We also want to make sue the db does not continue to accumulate too many event records. Consider adding logic to periodically remove old event records.

**Comment by gent1999** [comment]
Events table added, and ideas specific per event also integrated.
![image](https://github.com/user-attachments/assets/fd63d5f2-8d06-4638-9663-136a73212b79)
![image](https://github.com/user-attachments/assets/b7e65943-aa04-44f7-9126-da3a13b2a7ac)
