### ISSUE TITLE
Do a usability test

### ISSUE THREAD

**Issue by wilrnh** [flushingtech/Votte_Frontend#37]

**Comment by wilrnh** [comment]
thought this was an apt meme for this ticket 😂 

![Image](https://github.com/user-attachments/assets/0def7ae6-a325-4a81-9699-4aee59f6c626)

**Comment by adrianad2** [comment]
Here are my notes from the usability tests I conducted at the hackathon - [Votte Usability Tests](https://docs.google.com/document/d/1NksEnwvYE9Pic0Y0kHnCSBgLQVISl5y5n-JJpCh4ia8/edit?usp=sharing)

**TL;DR**

Users completed 3 different tasks based on our critical paths and user stories: 
1. Add an idea, 2. Edit an idea, 3. Like ideas

There were were 2 usability tests conducted, here are some key findings: 
- Users struggled to find the "Add Idea" button; it wasn’t clear or visible on the homepage.
- Confusion around which hackathon event to submit ideas for; dates aren’t clear.
- Users navigated unnecessarily to the homepage when already on the right page.
- Edit ideas functionality is missing or unclear.
- Users expected an edit option under “My Ideas.”
- Liking ideas is straightforward.

Design edits to be made: 
- Change to / add “add an idea” button 
- Make dates bigger and standout more 
- Add location and time info to event pages
- Move your submitted idea to the top of the list
