### ISSUE TITLE
Refresh Error

### ISSUE THREAD

**Issue by simk209** [flushingtech/Votte_Frontend#4]
Problem: On refresh, we are getting a 404 error.
My suspicion is that this is due to using react router. All routes are being handled by react router, and on refresh, the browser is making a request to the server, which is hitting out catch all 404 route. 

Potential solution: One solution may be serving the react app index.html in a catch all route, so that react router can handle it. However, I am unsure if this is feasible considering that we have two separate repos for frontend and backend. It may also be possible to leverage vercel to find a solution since both repos are hosted there.

Expected Behavior: No error on refresh.

**Comment by gent1999** [comment]
**Bug fixed.** When you refresh the page, the components just fetch again as if it were the first time being called. No error comes up now
