### ISSUE TITLE
Admin Credentials

### ISSUE THREAD

**Issue by simk209** [flushingtech/Votte_Frontend#5]
Admin credentials are needed to ensure that we can delete inappropriate posts. 

Possible Approach: Adding an "isAdmin" boolean field to the JWT. 

Considerations: Where do we store the admin emails? Hardcoded in the env? Seeding a database? What is a secure option?

**Comment by gent1999** [comment]
Admin emails added to an array in the eventsRoutes.js on the backend code
![image](https://github.com/user-attachments/assets/bff75fa8-1e39-48ac-b5be-87c095c20815)
